### ISSUE TITLE
Opportunities.insert_or_update has race conditions

### ISSUE THREAD

**Issue by jeffweiss** [elixirschool/extracurricular#35]
# Overview
Similar to the `Project.get_or_insert` race condition described in #29, `Opportunities.insert_or_update` has two distinct race conditions, one related to interleaving that can likely be solved in a manner like #31, and one related to out-of-order message delivery that will likely require discussion for the best approach. Because the discussion and remediation for the out-of-order race condition may affect the interleaving race condition, I chose to keep them together as a single issue rather than break them out as distinct issues.

## Interleaving race condition
Let's suppose that we have two messages for the same net new Opportunity arriving virtually simultaneously. Not out of the realm of possibility if someone opens a new issue and then adds a label like `Note: Discussion`.

```
    Payload A           Payload B
       |                   |
    create                 |
       |                create
    process_issue          |
       |              process_issue
    insert_or_update       |
       |               insert_or_update
    get -> nil             |
       |               get -> nil
    insert                 |
                        insert
 
```

### Steps to reproduce
The easiest way to reproduce the interleaving race condition effects is to repeatedly call `Opportunities.insert` with the same payload.

```
iex> %{title: "wat", url: "https://github.com/wat/wat/issue/1", level: "advanced", project_id: 1} |> Data.Opportunities.insert
iex> %{title: "wat", url: "https://github.com/wat/wat/issue/1", level: "advanced", project_id: 1} |> Data.Opportunities.insert
```

### Expected outcome

```
iex> %{title: "wat", url: "https://github.com/wat/wat/issue/1", level: "advanced", project_id: 1} |> Data.Opportunities.insert
{:ok,
 %Data.Opportunity{__meta__: #Ecto.Schema.Metadata<:loaded, "opportunities">,
  closed_at: nil, id: 1, inserted_at: ~N[2017-08-27 08:13:58.542228],
  level: "advanced",
  project: #Ecto.Association.NotLoaded<association :project is not loaded>,
  project_id: 1, title: "wat", updated_at: ~N[2017-08-27 08:13:58.542240],
  url: "https://github.com/wat/wat/issue/1"}}
iex> %{title: "wat", url: "https://github.com/wat/wat/issue/1", level: "advanced", project_id: 1} |> Data.Opportunities.insert
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * unique: opportunities_url

If you would like to convert this constraint into an error, please
call unique_constraint/3 in your changeset and define the proper
constraint name. The changeset has not defined any constraint.

    (ecto) lib/ecto/repo/schema.ex:570: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/repo/schema.ex:555: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto) lib/ecto/repo/schema.ex:219: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:768: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
```

### Actual outcome
```
iex> %{title: "wat", url: "https://github.com/wat/wat/issue/1", level: "advanced", project_id: 1} |> Data.Opportunities.insert
{:ok,
 %Data.Opportunity{__meta__: #Ecto.Schema.Metadata<:loaded, "opportunities">,
  closed_at: nil, id: 1, inserted_at: ~N[2017-08-27 08:13:58.542228],
  level: "advanced",
  project: #Ecto.Association.NotLoaded<association :project is not loaded>,
  project_id: 1, title: "wat", updated_at: ~N[2017-08-27 08:13:58.542240],
  url: "https://github.com/wat/wat/issue/1"}}
iex> %{title: "wat", url: "https://github.com/wat/wat/issue/1", level: "advanced", project_id: 1} |> Data.Opportunities.insert
{:ok,
 %Data.Opportunity{__meta__: #Ecto.Schema.Metadata<:loaded, "opportunities">,
  closed_at: nil, id: 2, inserted_at: ~N[2017-08-27 08:14:00.871934],
  level: "advanced",
  project: #Ecto.Association.NotLoaded<association :project is not loaded>,
  project_id: 1, title: "wat", updated_at: ~N[2017-08-27 08:14:00.871942],
  url: "https://github.com/wat/wat/issue/1"}}
```

## Out-of-order message delivery race condition
Let's suppose we have two issue changes for the same issue. For this case, let's presume someone accidentally closed an issue and immediately reopened it. The messages are  `Closed` and `Reopened`. Given a variety of factors from distributed GitHub infrastructure to network delays to BEAM process scheduling, it's possible for these two messages to arrive outside the causal order of `Closed -> Reopened`.

The current implementation will blindly overwrite the Opportunity state of the causally-later-but-delivered-first `Reopened` message with the causally-earlier-but-delivered-second `Closed` message. In which case, we now have a state conflict between our system (`Closed`) and GitHub (`Reopened`).

[IssueEvent](https://developer.github.com/v3/activity/events/types/#issuesevent) appears to contain an `updated_at` that we might be able to compare against what we have in the database to see if we have already consumed a causally-later message, but we either need to **explicitly** synchronize `updated_at` in our table with the one from the message (which seems potentially error-prone for maintentance and new-comers) or add a new column with GitHub's `updated_at` timestamp. I'm still not 100% comfortable with using wall-clock time from GitHub for inferring causal ordering, but it appears as though we don't have anything better is the message payload (perhaps in the headers?).

Thoughts?

**Comment by doomspork** [comment]
@jeffweiss you're on top of it, thanks!

I fear this comment is going to make you wince a little: I am aware of these issues and we're intentionally not trying to fix them all — yet.  With the goal of the project being to build a tool that is beneficial to the community and to do so while benefiting the community, we need to leave some "hiccups" behind so serve as learning opportunities in the future.

The primary goal right now is to work through the basic set of features, launch the project, and incrementally make it better as a group.  Some of that will include bugs popping up and working through them so we can all learn not only how to fix them but why they were a problem in the first place; these are the things we intend to blog about.  I think the end result of that will be a more educational experience as people will be able to follow along and learn the lessons you'd learn if you jumped into a new project.

To me, it's much like a job: If you work somewhere where the experienced members handles all the bugs and big problems you will be afforded few if any opportunities to learn and grow.

We should go ahead and patch this one but I'd like to hold off moving forward with creating issues for bugs that haven't come up yet as that eliminates our chance to teach around it.

I'd love for you to join @ybur-yug and I in the #elixirschool Slack channel to discuss some of the features and approach we're taking.  It's clear you're got a lot to offer and we should make sure we make the most of it 😀

**Comment by jeffweiss** [comment]
It doesn't have to be fixed right now just because I brought it up. 🤣
Part of my explicit descriptions has been to highlight some of the non-obvious errors when moving to Elixir/Erlang's concurrently model and also how Phoenix leverages it with a process per connection. I tried to take a step back and say "here's how it will happen."

I won't be offended if it's not fixed right now.

**Comment by treble37** [comment]
Hi, so I took a stab at part 1 of this issue via https://github.com/elixirschool/extracurricular/pull/85, but from this --

> but we either need to explicitly synchronize updated_at in our table with the one from the message (which seems potentially error-prone for maintentance and new-comers) or add a new column with GitHub's updated_at timestamp. I'm still not 100% comfortable with using wall-clock time from GitHub for inferring causal ordering, but it appears as though we don't have anything better is the message payload (perhaps in the headers?).

-- it seems like we are deciding between the choices. Was there one ever decided upon?
